//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentHelper.WinFormsUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgentHelper.WinFormsUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Cisco\Desktop\log\Agent0001.log.
        /// </summary>
        internal static string AgentLogFilePath64 {
            get {
                return ResourceManager.GetString("AgentLogFilePath64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Cisco\Desktop\log\Agent0001.log.
        /// </summary>
        internal static string AgentLogFilePath86 {
            get {
                return ResourceManager.GetString("AgentLogFilePath86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IfWinExist Logout - Cisco Agent Desktop
        ///{
        ///    WinActivate
        ///	Send ^l
        ///	WinWaitActive Agent Login
        ///	Send [PASSCODE]{Enter}
        ///}.
        /// </summary>
        internal static string AhkLoginScript {
            get {
                return ResourceManager.GetString("AhkLoginScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogInAgent.ahk.
        /// </summary>
        internal static string AhkScriptLogin {
            get {
                return ResourceManager.GetString("AhkScriptLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOutAgent.ahk.
        /// </summary>
        internal static string AhkScriptLogOut {
            get {
                return ResourceManager.GetString("AhkScriptLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout - Cisco Agent Desktop.
        /// </summary>
        internal static string CiscoWindowTitleLoggedOut {
            get {
                return ResourceManager.GetString("CiscoWindowTitleLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Ready - Cisco Agent Desktop.
        /// </summary>
        internal static string CiscoWindowTitleNotReady {
            get {
                return ResourceManager.GetString("CiscoWindowTitleNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready - Cisco Agent Desktop.
        /// </summary>
        internal static string CiscoWindowTitleReady {
            get {
                return ResourceManager.GetString("CiscoWindowTitleReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GreenPhone {
            get {
                object obj = ResourceManager.GetObject("GreenPhone", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon OrangePhone {
            get {
                object obj = ResourceManager.GetObject("OrangePhone", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon RedPhone {
            get {
                object obj = ResourceManager.GetObject("RedPhone", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
