//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentHelper.WinFormsUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgentHelper.WinFormsUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Cisco\Desktop\bin\agent.exe.
        /// </summary>
        internal static string AgentExeLocation64 {
            get {
                return ResourceManager.GetString("AgentExeLocation64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Cisco\Desktop\bin\agent.exe.
        /// </summary>
        internal static string AgentExeLocation86 {
            get {
                return ResourceManager.GetString("AgentExeLocation86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AhkBringUpLoginDialog.ahk.
        /// </summary>
        internal static string AhkFileNameBringUpLoginDialog {
            get {
                return ResourceManager.GetString("AhkFileNameBringUpLoginDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AhkCloseAgent.ahk.
        /// </summary>
        internal static string AhkFileNameCloseAgent {
            get {
                return ResourceManager.GetString("AhkFileNameCloseAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AhkLoggedInToLoggedOut.ahk.
        /// </summary>
        internal static string AhkFileNameLoggedInToLoggedOut {
            get {
                return ResourceManager.GetString("AhkFileNameLoggedInToLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AhkLoggedOutToLoggedIn.ahk.
        /// </summary>
        internal static string AhkFileNameLoggedOutToLoggedIn {
            get {
                return ResourceManager.GetString("AhkFileNameLoggedOutToLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AhkNotReadyToReady.ahk.
        /// </summary>
        internal static string AhkFileNameNotReadyToReady {
            get {
                return ResourceManager.GetString("AhkFileNameNotReadyToReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AhkReadyToNotReady.ahk.
        /// </summary>
        internal static string AhkFileNameReadyToNotReady {
            get {
                return ResourceManager.GetString("AhkFileNameReadyToNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AhkRunAgent.ahk.
        /// </summary>
        internal static string AhkFileNameRunAgent {
            get {
                return ResourceManager.GetString("AhkFileNameRunAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AhkTypeInPasswordToLogIn.ahk.
        /// </summary>
        internal static string AhkFileNameTypeInPasswordToLogIn {
            get {
                return ResourceManager.GetString("AhkFileNameTypeInPasswordToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IfWinExist, Logout - Cisco Agent Desktop
        ///{
        ///	ControlSend, ,^l, Logout - Cisco Agent Desktop
        ///	WinWait, Agent Login, , 4
        ///	WinActivate, Agent Login
        ///	Send [PASSCODE]{Enter}
        ///	if ErrorLevel
        ///	{
        ///		MsgBox, Couldn&apos;t Log in
        ///		return
        ///	}
        ///}.
        /// </summary>
        internal static string AhkScriptLoggedOutToLoggedIn {
            get {
                return ResourceManager.GetString("AhkScriptLoggedOutToLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run, agent.exe, C:\Program Files (x86)\Cisco\Desktop\bin\
        ///WinWait, Agent Login
        ///WinActivate
        ///Send [PASSCODE]{Enter}.
        /// </summary>
        internal static string AhkScriptRunAgent {
            get {
                return ResourceManager.GetString("AhkScriptRunAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IfWinExist, Agent Login
        ///{
        ///    WinActivate
        ///	Send, [PASSCODE]{Enter}
        ///}
        ///else
        ///{
        ///	WinWaitActive, Agent Login
        ///	Send, [PASSCODE]{Enter}
        ///}.
        /// </summary>
        internal static string AhkScriptTypeInPasswordToLogIn {
            get {
                return ResourceManager.GetString("AhkScriptTypeInPasswordToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout - Cisco Agent Desktop.
        /// </summary>
        internal static string CiscoWindowTitleLoggedOut {
            get {
                return ResourceManager.GetString("CiscoWindowTitleLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string CiscoWindowTitleLoginDialog {
            get {
                return ResourceManager.GetString("CiscoWindowTitleLoginDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Ready - Cisco Agent Desktop.
        /// </summary>
        internal static string CiscoWindowTitleNotReady {
            get {
                return ResourceManager.GetString("CiscoWindowTitleNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready - Cisco Agent Desktop.
        /// </summary>
        internal static string CiscoWindowTitleReady {
            get {
                return ResourceManager.GetString("CiscoWindowTitleReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ErrorIcon {
            get {
                object obj = ResourceManager.GetObject("ErrorIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorImage {
            get {
                object obj = ResourceManager.GetObject("ErrorImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GrayPhone {
            get {
                object obj = ResourceManager.GetObject("GrayPhone", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GreenPhone {
            get {
                object obj = ResourceManager.GetObject("GreenPhone", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenPhoneImage {
            get {
                object obj = ResourceManager.GetObject("GreenPhoneImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon OrangePhone {
            get {
                object obj = ResourceManager.GetObject("OrangePhone", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon RedPhone {
            get {
                object obj = ResourceManager.GetObject("RedPhone", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
