//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentHelper.WinFormsUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMinimizeNotification {
            get {
                return ((bool)(this["ShowMinimizeNotification"]));
            }
            set {
                this["ShowMinimizeNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int IdleMinsBeforeLoggingOut {
            get {
                return ((int)(this["IdleMinsBeforeLoggingOut"]));
            }
            set {
                this["IdleMinsBeforeLoggingOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456")]
        public string CiscoPassword {
            get {
                return ((string)(this["CiscoPassword"]));
            }
            set {
                this["CiscoPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogInAfterIdle {
            get {
                return ((bool)(this["LogInAfterIdle"]));
            }
            set {
                this["LogInAfterIdle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Cisco\\Desktop\\bin\\agent.exe")]
        public string CiscoAgentExeFileLocation {
            get {
                return ((string)(this["CiscoAgentExeFileLocation"]));
            }
            set {
                this["CiscoAgentExeFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NotReady")]
        public global::AgentHelper.WinFormsUI.AgentStatus LogInAfterIdleToStatus {
            get {
                return ((global::AgentHelper.WinFormsUI.AgentStatus)(this["LogInAfterIdleToStatus"]));
            }
            set {
                this["LogInAfterIdleToStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangeStatusOnScreenLock {
            get {
                return ((bool)(this["ChangeStatusOnScreenLock"]));
            }
            set {
                this["ChangeStatusOnScreenLock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NotReady")]
        public global::AgentHelper.WinFormsUI.AgentStatus ChangeStatusOnScreenLockTo {
            get {
                return ((global::AgentHelper.WinFormsUI.AgentStatus)(this["ChangeStatusOnScreenLockTo"]));
            }
            set {
                this["ChangeStatusOnScreenLockTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangeStatusOnScreenUnlock {
            get {
                return ((bool)(this["ChangeStatusOnScreenUnlock"]));
            }
            set {
                this["ChangeStatusOnScreenUnlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NotReady")]
        public global::AgentHelper.WinFormsUI.AgentStatus ChangeStatusOnScreenUnlockTo {
            get {
                return ((global::AgentHelper.WinFormsUI.AgentStatus)(this["ChangeStatusOnScreenUnlockTo"]));
            }
            set {
                this["ChangeStatusOnScreenUnlockTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogInOnStartup {
            get {
                return ((bool)(this["LogInOnStartup"]));
            }
            set {
                this["LogInOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NotReady")]
        public global::AgentHelper.WinFormsUI.AgentStatus LogInOnStartupTo {
            get {
                return ((global::AgentHelper.WinFormsUI.AgentStatus)(this["LogInOnStartupTo"]));
            }
            set {
                this["LogInOnStartupTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogOutAndCloseAgentOnShutDown {
            get {
                return ((bool)(this["LogOutAndCloseAgentOnShutDown"]));
            }
            set {
                this["LogOutAndCloseAgentOnShutDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogOutOnIdle {
            get {
                return ((bool)(this["LogOutOnIdle"]));
            }
            set {
                this["LogOutOnIdle"] = value;
            }
        }
    }
}
